repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.11
    hooks:
      - id: uv-lock
      - id: uv-export
        args:
          - --no-hashes
          - --no-header 
          - --no-annotate 
          - --no-dev
          - --no-emit-project
          - --output-file=app/requirements.txt

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black (python)
        language_version: python3
        files: ^(app/|tests/)
        args: [--line-length=135]